spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
    driverClassName: org.h2.Driver

weather:
  url: https://rapidapi.p.rapidapi.com/forecast/daily
  host: community-open-weather-map.p.rapidapi.com
  key: 1070a70177mshe8122f44fe533cbp1586fdjsn64e525b9963c
  unit: metric
  days: 8